
spring:
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
      username: ${usernameConfigServer}
      password: ${passwordConfigServer}